### PR TITLE
Implement Infinite Scrolling

### PR DESCRIPTION
**Pull request by KarthikRaju391**
- Moved API fetching from `JourneyList` component to `JourneyTable` and `JourneyCards`  respectively
- Used `useInfiniteQuery` to fetch journeys infinitely
- Used `react-intesection-observer` for infinite scrolliing

### CODE REVIEW

**Comment by KarthikRaju391** [comment]
@noahflk, I have implemented infinite scrolling on both mobile and desktop components. 
The delete request might need to be moved from `JourneyTable` to the respective mobile and desktop components. 
I can change the loading animations if you want me to...

**Comment by KarthikRaju391** [comment]
@noahflk , I tried to pull the changes from the main branch but I didn't get any changes. If you are working on a different branch, let me know so that I can pull the changes from that branch.

**Comment by KarthikRaju391** [comment]
Also, the loading animation is updated! If you can confirm regarding the conflicts I will push the changes

**Comment by noahflk** [comment]
> @noahflk , I tried to pull the changes from the main branch but I didn't get any changes. If you are working on a different branch, let me know so that I can pull the changes from that branch.

All good, we can fix it during merging. Please push the loading animation, then we can merge :)

**Comment by KarthikRaju391** [comment]
@noahflk, I needed to ask about the delete feature. Now that the delete API request is in `JourneyList` component, when the journey is deleted, it is not being updated unless the page is refreshed. Should I move the delete API request to the `JourneyTable` and `JourneyCard` component?

**Comment by noahflk** [comment]
@KarthikRaju391 try adding this to the delete `onSettled`:

```ts
utils.infiniteJourneys.get.invalidate();
```

**Comment by KarthikRaju391** [comment]
@noahflk, thanks for the help! I will push the changes now.

**Comment by KarthikRaju391** [comment]
@noahflk, I have pushed the latest changes.

**Comment by noahflk** [comment]
@KarthikRaju391 looks great, thank you very much!

I'll merge it to a temporary branch now, take care of the merge issues there and then deploy it on main 🎉

**Comment by KarthikRaju391** [comment]
@noahflk, that's amazing! I have learned a lot during the past few days. Thank you!

**Pull request merged**
